(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const startBtn = $('startBtn'), clearBtn = $('clearBtn'), copyBtn = $('copyBtn'), downloadBtn = $('downloadBtn');
  const logBox = $('log'), outputBox = $('output'), statusLabel = $('runtimeStatus'), packageState = $('packageState');
  const apiBaseInput = $('apiBaseInput'), saveApiBtn = $('saveApiBtn'), apiHealthBtn = $('apiHealthBtn');
  const voiceBtn = $('voiceBtn'), youtubeAuthBtn = $('youtubeAuthBtn'), uploadTestBtn = $('uploadTestBtn'), fullBuildBtn = $('fullBuildBtn'), apiState = $('apiState');
  let latestPackage = null, runId = 0;
  const clean = (v) => String(v ?? '').replace(/[<>]/g, '').trim();
  const nowLabel = () => new Date().toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const apiBase = () => (localStorage.getItem('zztv.apiBase') || '').replace(/\/$/, '');
  const apiUrl = (p) => `${apiBase()}${p}`;
  function log(m, t = 'info') { const i = t === 'pass' ? '✅' : t === 'warn' ? '⚠️' : t === 'fail' ? '❌' : '•'; logBox.textContent += `\n${i} ${m}`; logBox.scrollTop = logBox.scrollHeight; }
  function setStatus(m) { statusLabel.textContent = m; }
  function setApiState(m, t = '') { apiState.textContent = m; apiState.classList.remove('ready', 'warn'); if (t) apiState.classList.add(t); }
  function saveApiBase() { const v = (apiBaseInput.value || '').trim().replace(/\/$/, ''); if (!v) { localStorage.removeItem('zztv.apiBase'); setApiState('Same-origin', 'warn'); log('Same-site /api mode enabled.', 'warn'); return; } try { new URL(v); localStorage.setItem('zztv.apiBase', v); setApiState('Saved', 'ready'); log(`Saved backend URL: ${v}`, 'pass'); } catch { setApiState('Bad URL', 'warn'); log('Invalid backend URL.', 'fail'); } }
  async function checkApiHealth() { try { setApiState('Checking', 'warn'); const r = await fetch(apiUrl('/api/health')); const d = await r.json(); if (!r.ok || !d.ok) throw new Error(d.error || `HTTP ${r.status}`); setApiState('API online', 'ready'); log(`API online: OpenAI=${d.env.openaiReady}, YouTubeUpload=${d.env.youtubeUploadReady}, TikTok=${d.env.tiktokConfigured}`, 'pass'); return d; } catch (e) { setApiState('API offline', 'warn'); log(`API health failed: ${e.message}`, 'warn'); return null; } }
  function pick(a) { return a[Math.floor(Math.random() * a.length)]; }
  function fallbackPackage() { const sports = ['basketball','soccer','football','baseball','track']; const sport = pick(sports); const angle = pick(['confidence and teamwork','staying calm after mistakes','fast feet and smart decisions','practice habits that actually work']); const hook = `Most players miss this ${sport} lesson.`; return { runId, createdAt: nowLabel(), channel: 'ZZTV Sports', mode: 'Caption-first private upload', youtube: { title: `ZZTV: ${angle} 🏆`, description: `A safe ZZTV sports short about ${angle}. Practice hard and keep improving.`, tags: ['sports tips','youth sports',sport,'ZZTV'], visibility: 'private' }, script: ['Welcome back to ZZTV!', hook, `Today: ${angle}.`, 'Start slow and keep it clean.', 'Speed up only when it feels easy.', 'Stay positive and help your team.', 'Follow ZZTV for more.'], tiktok: { caption: `${hook} Practice smarter today 🏆 #ZZTV`, hashtags: ['#sportstips','#youthsports','#ZZTV'] }, soundProduction: { narration: 'Optional voice button only', music: 'caption-first safe release' }, videoPlan: { format: '9:16 vertical', duration: '8 seconds', scenes: ['intro','caption cards','follow card'] }, schedule: { youtubeShorts: 'private-first', tiktok: 'draft review' } }; }
  function normalizePackage(p) { const f = fallbackPackage(); return { ...f, ...p, mode: 'Caption-first private upload', youtube: { ...f.youtube, ...(p?.youtube || {}) }, script: Array.isArray(p?.script) ? p.script : f.script, tiktok: { ...f.tiktok, ...(p?.tiktok || {}) }, soundProduction: { ...f.soundProduction, ...(p?.soundProduction || p?.sound || {}) }, videoPlan: { ...f.videoPlan, ...(p?.videoPlan || p?.video || {}) } }; }
  async function generatePackage() { const r = await fetch(apiUrl('/api/generate-package'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sport: 'basketball', angle: 'confidence and teamwork for young athletes' }) }); const d = await r.json(); if (!r.ok || !d.ok) throw new Error(d.error || d.message || `HTTP ${r.status}`); return normalizePackage(d.package); }
  function renderPackage(p) { outputBox.innerHTML = `<div class="kv"><div><b>Status:</b><br>Ready. Full Build skips paid voice and uses large captions.</div><div><b>YouTube Title:</b><br>${clean(p.youtube.title)}</div><div><b>Script:</b><br>${p.script.map((x,i)=>`${i+1}. ${clean(x)}`).join('<br>')}</div><div><b>TikTok Caption:</b><br>${clean(p.tiktok.caption)}</div><div><b>Hashtags:</b><br>${(p.tiktok.hashtags||[]).map(clean).join(' ')}</div></div>`; packageState.textContent = 'Ready'; packageState.classList.add('ready'); }
  async function runZZTV(e) { e?.preventDefault(); if (startBtn.disabled) return; runId++; startBtn.disabled = true; packageState.textContent = 'Running'; packageState.classList.remove('ready'); logBox.textContent = `Run ${runId} started at ${nowLabel()}`; outputBox.textContent = 'Generating package...'; setStatus('Running...'); for (const x of ['Tap received','JavaScript loaded','Safety guard enabled','Private-first guard enabled','Caption-first mode enabled']) { await sleep(80); log(x,'pass'); } try { latestPackage = await generatePackage(); log('Generated package through backend API','pass'); } catch (e2) { latestPackage = fallbackPackage(); log(`Backend fallback used: ${e2.message}`,'warn'); } localStorage.setItem('zztv.latestPackage', JSON.stringify(latestPackage,null,2)); renderPackage(latestPackage); log('START ZZTV PASSED','pass'); setStatus('Package ready.'); startBtn.disabled = false; }
  async function openYouTubeAuth() { try { const r = await fetch(apiUrl('/api/youtube/auth-url')); const d = await r.json(); if (!r.ok || !d.ok || !d.url) throw new Error(d.message || d.error || 'No auth URL'); window.open(d.url, '_blank', 'noopener,noreferrer'); log('Opened YouTube OAuth URL','pass'); } catch(e) { log(`YouTube auth not ready: ${e.message}`,'warn'); } }
  async function makeVoice() { const p = latestPackage || JSON.parse(localStorage.getItem('zztv.latestPackage') || 'null'); if (!p) { log('Run ZZTV first.','warn'); return; } try { setStatus('Requesting optional voice...'); const r = await fetch(apiUrl('/api/tts'), { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ script:p.script, voice:'coral' }) }); const type = r.headers.get('content-type') || ''; if (type.includes('application/json')) { const d = await r.json().catch(()=>({})); throw new Error(d.error || d.message || d.warning || 'Voice unavailable'); } if (!r.ok) throw new Error(`HTTP ${r.status}`); const blob = await r.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `zztv-voice-${Date.now()}.mp3`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); log('Optional voice MP3 downloaded','pass'); } catch(e) { log(`Voice optional/unavailable: ${e.message}`,'warn'); log('Full Build still works with captions.','pass'); } }
  function bestVideoType(){ if(!window.MediaRecorder) return ''; return ['video/mp4;codecs=h264','video/mp4','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t)) || ''; }
  function wrap(ctx,text,x,y,w,lh,max=3){ const words=clean(text).split(/\s+/).filter(Boolean); const lines=[]; let cur=''; for(const word of words){ const n=cur?`${cur} ${word}`:word; if(ctx.measureText(n).width>w && cur){ lines.push(cur); cur=word; } else cur=n; if(lines.length>=max) break; } if(cur && lines.length<max) lines.push(cur); lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lh)); }
  function draw(ctx,c,elapsed,total,p,test=false){ const pr=Math.min(1,elapsed/total), w=c.width, h=c.height, pulse=Math.sin(pr*Math.PI*8)*0.5+0.5; const script=p.script||[]; const line=script[Math.min(script.length-1,Math.floor(pr*Math.max(1,script.length)))] || 'Practice smarter today.'; const bg=ctx.createLinearGradient(0,0,w,h); bg.addColorStop(0,'#070707'); bg.addColorStop(.45,'#241805'); bg.addColorStop(1,'#000'); ctx.fillStyle=bg; ctx.fillRect(0,0,w,h); ctx.fillStyle=`rgba(255,220,115,${.12+pulse*.12})`; ctx.beginPath(); ctx.arc(w*.78,h*.15,95+pulse*25,0,Math.PI*2); ctx.fill(); ctx.textAlign='center'; ctx.fillStyle='#ffdc73'; ctx.font='900 66px Arial'; ctx.fillText('ZZTV',w/2,96); ctx.fillStyle='#fff7db'; ctx.font='800 18px Arial'; ctx.fillText(test?'PRIVATE TEST':'CAPTION-FIRST PRIVATE BUILD',w/2,132); ctx.strokeStyle='rgba(255,220,115,.55)'; ctx.lineWidth=4; ctx.strokeRect(24,165,w-48,320); ctx.fillStyle='#ffdc73'; ctx.font='800 22px Arial'; ctx.fillText('Sports Short',w/2,210); ctx.fillStyle='#fff7db'; ctx.font='800 23px Arial'; wrap(ctx,p.youtube?.title||'ZZTV Sports Short',w/2,255,w-74,29,2); ctx.fillStyle='rgba(0,0,0,.38)'; ctx.fillRect(38,326,w-76,120); ctx.fillStyle='#fff7db'; ctx.font='900 24px Arial'; wrap(ctx,line,w/2,365,w-86,31,3); ctx.fillStyle='#ffdc73'; ctx.font='900 78px Arial'; ctx.fillText('🏀',48+pr*(w-96),535+Math.sin(pr*Math.PI*4)*30); ctx.fillStyle='#fff7db'; ctx.font='800 24px Arial'; ctx.fillText('Practice smarter today',w/2,586); ctx.fillStyle='#47d16c'; ctx.fillRect(45,614,(w-90)*pr,10); }
  async function makeVideo(p,{test=false}={}){ if(!window.MediaRecorder) throw new Error('MediaRecorder unsupported'); const canvas=document.createElement('canvas'); canvas.width=360; canvas.height=640; const ctx=canvas.getContext('2d'); if(!ctx || !canvas.captureStream) throw new Error('Canvas capture unsupported'); const dur=test?3200:8200, stream=canvas.captureStream(24), type=bestVideoType(), opts={videoBitsPerSecond:test?350000:680000}; if(type) opts.mimeType=type; return new Promise((res,rej)=>{ const chunks=[]; let rec,done=false; const stop=()=>stream.getTracks().forEach(t=>t.stop()); const fail=e=>{ if(done)return; done=true; stop(); rej(e); }; try{ rec=new MediaRecorder(stream,opts); }catch{ try{ rec=new MediaRecorder(stream); }catch(e){ fail(e); return; } } rec.ondataavailable=e=>{ if(e.data?.size) chunks.push(e.data); }; rec.onerror=()=>fail(new Error('Recorder failed')); rec.onstop=()=>{ if(done)return; done=true; stop(); res(new Blob(chunks,{type:rec.mimeType||type||'video/webm'})); }; const start=performance.now(); const frame=now=>{ const el=now-start; draw(ctx,canvas,el,dur,p,test); if(el<dur && !done) requestAnimationFrame(frame); }; draw(ctx,canvas,0,dur,p,test); rec.start(250); requestAnimationFrame(frame); setTimeout(()=>{ try{ if(rec.state!=='inactive') rec.stop(); }catch(e){ fail(e); } },dur+350); setTimeout(()=>{ if(!done) fail(new Error('Video render timed out')); },dur+3500); }); }
  async function blobUrl(blob){ return new Promise((res,rej)=>{ const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=()=>rej(r.error||new Error('Blob read failed')); r.readAsDataURL(blob); }); }
  async function upload(blob,p,{test=false}={}){ const r=await fetch(apiUrl('/api/youtube/upload-direct'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ dataUrl:await blobUrl(blob), title:test?'ZZTV Private Test Upload':p.youtube.title, description:test?'Private upload test.':`${p.youtube.description}\n\nCaption-first private upload by ZZTV for review.`, tags:test?['ZZTV','private test']:p.youtube.tags, privacyStatus:'private', selfDeclaredMadeForKids:true })}); const d=await r.json().catch(()=>({})); if(!r.ok||!d.ok){ const detail=d.detail||{}; const err=Object.assign(new Error(d.message||detail.message||d.error||`HTTP ${r.status}`),{reason:d.reason||detail.reason,status:d.status||detail.status||r.status}); throw err; } return d; }
  async function uploadTest(){ if(uploadTestBtn.disabled)return; const h=await checkApiHealth(); if(!h?.env?.youtubeUploadReady){ log('YouTube upload not ready.','fail'); return; } const p=latestPackage||JSON.parse(localStorage.getItem('zztv.latestPackage')||'null')||fallbackPackage(); latestPackage=p; try{ uploadTestBtn.disabled=true; log('Rendering private test video...','warn'); const b=await makeVideo(p,{test:true}); log(`Rendered test: ${Math.round(b.size/1024)} KB, ${b.type}`,'pass'); log('Uploading private test...','warn'); const d=await upload(b,p,{test:true}); log(`Private test upload PASSED: ${d.url}`,'pass'); if(d.studioUrl) log(`Studio edit link: ${d.studioUrl}`,'pass'); }catch(e){ log(`Private upload failed: ${e.message}`,'fail'); if(e.reason)log(`YouTube reason: ${e.reason}`,'fail'); if(e.status)log(`YouTube status: ${e.status}`,'fail'); }finally{ uploadTestBtn.disabled=false; } }
  async function fullBuild(){ if(fullBuildBtn.disabled)return; const h=await checkApiHealth(); if(!h?.env?.youtubeUploadReady){ log('Full build blocked: YouTube upload not ready.','fail'); return; } try{ fullBuildBtn.disabled=uploadTestBtn.disabled=startBtn.disabled=true; logBox.textContent=`Full Private Build started at ${nowLabel()}`; setStatus('Generating package...'); try{ latestPackage=await generatePackage(); log('Generated package with backend','pass'); }catch(e){ latestPackage=fallbackPackage(); log(`Package fallback used: ${e.message}`,'warn'); } renderPackage(latestPackage); localStorage.setItem('zztv.latestPackage',JSON.stringify(latestPackage,null,2)); log('Caption-first mode active: paid voice is skipped so quota cannot block upload.','pass'); log('The script is rendered as large on-screen captions.','pass'); setStatus('Rendering captions...'); const b=await makeVideo(latestPackage,{test:false}); log(`Rendered caption-first video: ${Math.round(b.size/1024)} KB, ${b.type}`,'pass'); setStatus('Uploading private video...'); const d=await upload(b,latestPackage,{test:false}); log(`FULL PRIVATE BUILD PASSED: ${d.url}`,'pass'); if(d.studioUrl) log(`Studio review link: ${d.studioUrl}`,'pass'); setStatus('Private build uploaded. Review in Studio.'); }catch(e){ log(`Full Build failed: ${e.message}`,'fail'); if(e.reason)log(`YouTube reason: ${e.reason}`,'fail'); if(e.status)log(`YouTube status: ${e.status}`,'fail'); }finally{ fullBuildBtn.disabled=uploadTestBtn.disabled=startBtn.disabled=false; } }
  function copyPackage(){ const p=latestPackage||JSON.parse(localStorage.getItem('zztv.latestPackage')||'null'); if(!p){log('Run ZZTV first.','warn');return;} navigator.clipboard.writeText(JSON.stringify(p,null,2)).then(()=>log('Copied package','pass')).catch(e=>log(`Clipboard blocked: ${e.message}`,'warn')); }
  function downloadPackage(){ const p=latestPackage||JSON.parse(localStorage.getItem('zztv.latestPackage')||'null'); if(!p){log('Run ZZTV first.','warn');return;} const u=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=u; a.download=`zztv-package-${Date.now()}.json`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(u); log('Downloaded package JSON','pass'); }
  function clearRun(){ logBox.textContent='Waiting for START ZZTV...'; outputBox.textContent='No package generated yet.'; packageState.textContent='Empty'; packageState.classList.remove('ready'); setStatus('Ready. Live browser app loaded.'); }
  function boot(){ if(apiBaseInput)apiBaseInput.value=apiBase(); startBtn?.addEventListener('click',runZZTV); startBtn?.addEventListener('touchend',runZZTV,{passive:false}); clearBtn?.addEventListener('click',clearRun); copyBtn?.addEventListener('click',copyPackage); downloadBtn?.addEventListener('click',downloadPackage); saveApiBtn?.addEventListener('click',saveApiBase); apiHealthBtn?.addEventListener('click',checkApiHealth); voiceBtn?.addEventListener('click',makeVoice); youtubeAuthBtn?.addEventListener('click',openYouTubeAuth); uploadTestBtn?.addEventListener('click',uploadTest); fullBuildBtn?.addEventListener('click',fullBuild); if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>log('Offline worker not registered; app still works online','warn')); setApiState(apiBase()?'Saved':'Local mode',apiBase()?'ready':'warn'); setStatus('Ready. Live browser app loaded.'); }
  window.addEventListener('error',e=>{ log(`Browser error: ${e.message}`,'fail'); [startBtn,uploadTestBtn,fullBuildBtn].forEach(b=>{ if(b)b.disabled=false; }); });
  boot();
})();
